/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERC777Sender, IERC777SenderInterface } from "../IERC777Sender";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "operator",
        type: "address",
      },
      {
        name: "from",
        type: "address",
      },
      {
        name: "to",
        type: "address",
      },
      {
        name: "amount",
        type: "uint256",
      },
      {
        name: "userData",
        type: "bytes",
      },
      {
        name: "operatorData",
        type: "bytes",
      },
    ],
    name: "tokensToSend",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC777Sender__factory {
  static readonly abi = _abi;
  static createInterface(): IERC777SenderInterface {
    return new utils.Interface(_abi) as IERC777SenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC777Sender {
    return new Contract(address, _abi, signerOrProvider) as IERC777Sender;
  }
}
