/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AbstractUserInterface extends utils.Interface {
  functions: {
    "managerContract()": FunctionFragment;
    "userId()": FunctionFragment;
    "userInventory(uint256)": FunctionFragment;
    "addItemToInventory(uint256)": FunctionFragment;
    "checkInventory(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "managerContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "userId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userInventory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addItemToInventory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkInventory",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "managerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addItemToInventory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkInventory",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AbstractUser extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AbstractUserInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    managerContract(overrides?: CallOverrides): Promise<[string]>;

    userId(overrides?: CallOverrides): Promise<[string]>;

    userInventory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    addItemToInventory(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    checkInventory(
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  managerContract(overrides?: CallOverrides): Promise<string>;

  userId(overrides?: CallOverrides): Promise<string>;

  userInventory(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  addItemToInventory(
    itemId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  checkInventory(
    itemId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    managerContract(overrides?: CallOverrides): Promise<string>;

    userId(overrides?: CallOverrides): Promise<string>;

    userInventory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addItemToInventory(
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkInventory(
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    managerContract(overrides?: CallOverrides): Promise<BigNumber>;

    userId(overrides?: CallOverrides): Promise<BigNumber>;

    userInventory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addItemToInventory(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    checkInventory(
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    managerContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userInventory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addItemToInventory(
      itemId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    checkInventory(
      itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
