/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IndividuallyCappedCrowdsaleImplInterface
  extends utils.Interface {
  functions: {
    "getContribution(address)": FunctionFragment;
    "rate()": FunctionFragment;
    "isCapper(address)": FunctionFragment;
    "removeCapper(address)": FunctionFragment;
    "weiRaised()": FunctionFragment;
    "wallet()": FunctionFragment;
    "renounceCapper()": FunctionFragment;
    "setCap(address,uint256)": FunctionFragment;
    "addCapper(address)": FunctionFragment;
    "getCap(address)": FunctionFragment;
    "onlyCapperMock()": FunctionFragment;
    "buyTokens(address)": FunctionFragment;
    "token()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getContribution",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "rate", values?: undefined): string;
  encodeFunctionData(functionFragment: "isCapper", values: [string]): string;
  encodeFunctionData(
    functionFragment: "removeCapper",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "weiRaised", values?: undefined): string;
  encodeFunctionData(functionFragment: "wallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceCapper",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCap",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "addCapper", values: [string]): string;
  encodeFunctionData(functionFragment: "getCap", values: [string]): string;
  encodeFunctionData(
    functionFragment: "onlyCapperMock",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "buyTokens", values: [string]): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isCapper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeCapper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weiRaised", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceCapper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addCapper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onlyCapperMock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;

  events: {
    "CapperAdded(address)": EventFragment;
    "CapperRemoved(address)": EventFragment;
    "TokensPurchased(address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CapperAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CapperRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensPurchased"): EventFragment;
}

export type CapperAddedEvent = TypedEvent<[string], { account: string }>;

export type CapperAddedEventFilter = TypedEventFilter<CapperAddedEvent>;

export type CapperRemovedEvent = TypedEvent<[string], { account: string }>;

export type CapperRemovedEventFilter = TypedEventFilter<CapperRemovedEvent>;

export type TokensPurchasedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  {
    purchaser: string;
    beneficiary: string;
    value: BigNumber;
    amount: BigNumber;
  }
>;

export type TokensPurchasedEventFilter = TypedEventFilter<TokensPurchasedEvent>;

export interface IndividuallyCappedCrowdsaleImpl extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IndividuallyCappedCrowdsaleImplInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getContribution(
      beneficiary: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    rate(overrides?: CallOverrides): Promise<[BigNumber]>;

    isCapper(account: string, overrides?: CallOverrides): Promise<[boolean]>;

    removeCapper(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    weiRaised(overrides?: CallOverrides): Promise<[BigNumber]>;

    wallet(overrides?: CallOverrides): Promise<[string]>;

    renounceCapper(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCap(
      beneficiary: string,
      cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addCapper(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCap(
      beneficiary: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    onlyCapperMock(overrides?: CallOverrides): Promise<[void]>;

    buyTokens(
      beneficiary: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    token(overrides?: CallOverrides): Promise<[string]>;
  };

  getContribution(
    beneficiary: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  rate(overrides?: CallOverrides): Promise<BigNumber>;

  isCapper(account: string, overrides?: CallOverrides): Promise<boolean>;

  removeCapper(
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  weiRaised(overrides?: CallOverrides): Promise<BigNumber>;

  wallet(overrides?: CallOverrides): Promise<string>;

  renounceCapper(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCap(
    beneficiary: string,
    cap: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addCapper(
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCap(beneficiary: string, overrides?: CallOverrides): Promise<BigNumber>;

  onlyCapperMock(overrides?: CallOverrides): Promise<void>;

  buyTokens(
    beneficiary: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  token(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getContribution(
      beneficiary: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rate(overrides?: CallOverrides): Promise<BigNumber>;

    isCapper(account: string, overrides?: CallOverrides): Promise<boolean>;

    removeCapper(account: string, overrides?: CallOverrides): Promise<void>;

    weiRaised(overrides?: CallOverrides): Promise<BigNumber>;

    wallet(overrides?: CallOverrides): Promise<string>;

    renounceCapper(overrides?: CallOverrides): Promise<void>;

    setCap(
      beneficiary: string,
      cap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addCapper(account: string, overrides?: CallOverrides): Promise<void>;

    getCap(beneficiary: string, overrides?: CallOverrides): Promise<BigNumber>;

    onlyCapperMock(overrides?: CallOverrides): Promise<void>;

    buyTokens(beneficiary: string, overrides?: CallOverrides): Promise<void>;

    token(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CapperAdded(address)"(account?: string | null): CapperAddedEventFilter;
    CapperAdded(account?: string | null): CapperAddedEventFilter;

    "CapperRemoved(address)"(account?: string | null): CapperRemovedEventFilter;
    CapperRemoved(account?: string | null): CapperRemovedEventFilter;

    "TokensPurchased(address,address,uint256,uint256)"(
      purchaser?: string | null,
      beneficiary?: string | null,
      value?: null,
      amount?: null
    ): TokensPurchasedEventFilter;
    TokensPurchased(
      purchaser?: string | null,
      beneficiary?: string | null,
      value?: null,
      amount?: null
    ): TokensPurchasedEventFilter;
  };

  estimateGas: {
    getContribution(
      beneficiary: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rate(overrides?: CallOverrides): Promise<BigNumber>;

    isCapper(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    removeCapper(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    weiRaised(overrides?: CallOverrides): Promise<BigNumber>;

    wallet(overrides?: CallOverrides): Promise<BigNumber>;

    renounceCapper(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCap(
      beneficiary: string,
      cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addCapper(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCap(beneficiary: string, overrides?: CallOverrides): Promise<BigNumber>;

    onlyCapperMock(overrides?: CallOverrides): Promise<BigNumber>;

    buyTokens(
      beneficiary: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getContribution(
      beneficiary: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isCapper(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeCapper(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    weiRaised(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceCapper(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCap(
      beneficiary: string,
      cap: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addCapper(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCap(
      beneficiary: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onlyCapperMock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyTokens(
      beneficiary: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
